// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model.Repositories;

namespace Model.Migrations
{
    [DbContext(typeof(EFBankContext))]
    partial class EFBankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.2.20159.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Entities.Klant", b =>
                {
                    b.Property<int>("KlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("KlantId");

                    b.ToTable("Klanten");

                    b.HasData(
                        new
                        {
                            KlantId = 1,
                            Naam = "Marge"
                        },
                        new
                        {
                            KlantId = 2,
                            Naam = "Homer"
                        },
                        new
                        {
                            KlantId = 3,
                            Naam = "Lisa"
                        },
                        new
                        {
                            KlantId = 4,
                            Naam = "Maggie"
                        },
                        new
                        {
                            KlantId = 5,
                            Naam = "Bart"
                        });
                });

            modelBuilder.Entity("Model.Entities.Rekening", b =>
                {
                    b.Property<string>("RekeningNr")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("KlantId")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RekeningNr");

                    b.HasIndex("KlantId");

                    b.ToTable("Rekeningen");

                    b.HasData(
                        new
                        {
                            RekeningNr = "BE68123456789012",
                            KlantId = 1,
                            Saldo = 1000m
                        },
                        new
                        {
                            RekeningNr = "BE68234567890169",
                            KlantId = 1,
                            Saldo = 2000m
                        },
                        new
                        {
                            RekeningNr = "BE68345678901212",
                            KlantId = 2,
                            Saldo = 500m
                        });
                });

            modelBuilder.Entity("Model.Entities.Rekening", b =>
                {
                    b.HasOne("Model.Entities.Klant", "Klant")
                        .WithMany("Rekeningen")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
